"""Shared figure style for Propel.

Every figure in this repository is generated by a script in `figure_*/` that
imports this module. Nothing is hand-drawn, nothing is edited in Illustrator,
and no figure exists without the code that produced it. Structure follows
ChenLiu-1996/figures4papers: one folder per figure, the script beside its
outputs, a single shared style module.

The reason is the same reason Propel exists at all. A figure you cannot
regenerate is a claim you cannot re-check: when the pipeline gains a stage or a
mode changes which gates it runs, a hand-drawn SVG silently goes stale and
everyone keeps citing it. A script goes stale loudly — you edit one line and
re-run `make_all.py`.

Usage
-----
    import sys, pathlib
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
    from propel_style import PALETTE, apply_publication_style, finalize_figure
"""

from __future__ import annotations

from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

# ---------------------------------------------------------------------------
# Palette — matched to the Propel website so figures and page read as one system
# ---------------------------------------------------------------------------

PALETTE = {
    # neutrals
    "ink": "#1f2328",       # primary text
    "muted": "#57606a",     # secondary text
    "dim": "#8c959f",       # tertiary text, arrowheads
    "line": "#d8dee4",      # borders
    "rule": "#e5e7eb",      # hairlines
    "panel": "#f6f8fa",     # filled boxes
    "paper": "#ffffff",     # canvas
    # semantic
    "human": "#2563eb",     # anything the human owns — gates, decisions
    "human_soft": "#dbeafe",
    "machine": "#57606a",   # anything the machine executes
    "machine_soft": "#eef1f5",
    "codex": "#8b5cf6",     # the second model
    "codex_soft": "#f5f3ff",
    "warn": "#d97706",
    "bad": "#dc2626",
    "good": "#10b981",
    # modes (identical to the website's mode badges)
    "researcher": "#8b5cf6",
    "engineer": "#2563eb",
    "debugger": "#dc2626",
    "trainer": "#10b981",
}

FONT_STACK = [
    "Noto Sans",
    "Helvetica Neue",
    "Helvetica",
    "Arial",
    "DejaVu Sans",
]


def apply_publication_style(font_size: int = 10) -> None:
    """Set rcParams once, at the top of every figure script.

    Keeps text as real text in SVG and PDF (`svg.fonttype='none'`,
    `pdf.fonttype=42`) so it stays selectable, searchable, and re-styleable by
    the website's CSS rather than being frozen into outlines.
    """
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": FONT_STACK,
            "font.size": font_size,
            "text.color": PALETTE["ink"],
            "axes.edgecolor": PALETTE["line"],
            "axes.labelcolor": PALETTE["ink"],
            "axes.linewidth": 0.8,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "xtick.color": PALETTE["muted"],
            "ytick.color": PALETTE["muted"],
            "xtick.labelsize": font_size - 1,
            "ytick.labelsize": font_size - 1,
            "legend.frameon": False,
            "figure.facecolor": PALETTE["paper"],
            "axes.facecolor": PALETTE["paper"],
            "savefig.facecolor": PALETTE["paper"],
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


# ---------------------------------------------------------------------------
# Diagram primitives
# ---------------------------------------------------------------------------


def canvas(width: float, height: float):
    """A blank, unit-coordinate canvas (0..width, 0..height) with no axes."""
    fig, ax = plt.subplots(figsize=(width, height))
    ax.set_xlim(0, width)
    ax.set_ylim(0, height)
    ax.set_aspect("equal")
    ax.axis("off")
    fig.subplots_adjust(left=0, right=1, top=1, bottom=0)
    return fig, ax


def canvas_px(width_px: float, height_px: float, scale: float = 100.0):
    """A canvas whose data units are pixels, with y increasing downward.

    Diagram layouts are far easier to reason about in screen coordinates than in
    matplotlib's bottom-left origin, and it keeps these scripts comparable to the
    SVG they replaced. `scale` is pixels per inch of figure size.
    """
    fig, ax = plt.subplots(figsize=(width_px / scale, height_px / scale))
    ax.set_xlim(0, width_px)
    ax.set_ylim(height_px, 0)
    ax.set_aspect("equal")
    ax.axis("off")
    fig.subplots_adjust(left=0, right=1, top=1, bottom=0)
    return fig, ax


def box(
    ax,
    x: float,
    y: float,
    w: float,
    h: float,
    label: str,
    *,
    sublabel: str | None = None,
    face: str = PALETTE["panel"],
    edge: str = PALETTE["line"],
    text: str = PALETTE["ink"],
    lw: float = 1.0,
    radius: float = 0.06,
    fontsize: float = 9.5,
    weight: str = "bold",
    dashed: bool = False,
):
    """A rounded box with a centered label, placed by its bottom-left corner."""
    ax.add_patch(
        FancyBboxPatch(
            (x, y),
            w,
            h,
            boxstyle=f"round,pad=0,rounding_size={radius}",
            facecolor=face,
            edgecolor=edge,
            linewidth=lw,
            linestyle=(0, (3, 2)) if dashed else "solid",
            zorder=2,
        )
    )
    cy = y + h / 2 + (0.09 if sublabel else 0)
    ax.text(
        x + w / 2, cy, label,
        ha="center", va="center", fontsize=fontsize, color=text,
        fontweight=weight, zorder=3,
    )
    if sublabel:
        ax.text(
            x + w / 2, y + h / 2 - 0.16, sublabel,
            ha="center", va="center", fontsize=fontsize - 1.8,
            color=PALETTE["muted"], zorder=3,
        )


def arrow(
    ax,
    start: tuple[float, float],
    end: tuple[float, float],
    *,
    color: str = PALETTE["dim"],
    lw: float = 1.1,
    style: str = "-|>",
    curve: float = 0.0,
    dashed: bool = False,
    zorder: int = 1,
):
    ax.add_patch(
        FancyArrowPatch(
            start,
            end,
            arrowstyle=style,
            mutation_scale=10,
            color=color,
            linewidth=lw,
            linestyle=(0, (3, 2)) if dashed else "solid",
            connectionstyle=f"arc3,rad={curve}",
            shrinkA=0,
            shrinkB=0,
            zorder=zorder,
        )
    )


def elbow(
    ax,
    points: list[tuple[float, float]],
    *,
    color: str = PALETTE["dim"],
    lw: float = 1.0,
    dashed: bool = True,
    zorder: int = 1,
):
    """An orthogonal dashed path with an arrowhead on the last segment.

    Preferred over a curved arc for feedback loops: an arc's bulge direction
    depends on the axis orientation, which makes it easy to draw a loop that
    silently disappears behind a box. An elbow goes where you put it.
    """
    ls = (0, (3, 2)) if dashed else "solid"
    for a, b in zip(points, points[1:-1]):
        ax.plot([a[0], b[0]], [a[1], b[1]], color=color, lw=lw,
                linestyle=ls, solid_capstyle="round", zorder=zorder)
    arrow(ax, points[-2], points[-1], color=color, lw=lw, dashed=dashed,
          zorder=zorder)


def diamond(ax, cx: float, cy: float, r: float, *, face: str, edge: str, lw: float = 1.3):
    """A gate marker. Filled = the human decides here."""
    ax.add_patch(
        plt.Polygon(
            [(cx, cy + r), (cx + r, cy), (cx, cy - r), (cx - r, cy)],
            closed=True, facecolor=face, edgecolor=edge, linewidth=lw, zorder=4,
        )
    )


def title(ax, x: float, y: float, text: str, *, size: float = 11.5):
    ax.text(x, y, text, ha="left", va="center", fontsize=size,
            color=PALETTE["ink"], fontweight="bold")


def caption(ax, x: float, y: float, text: str, *, size: float = 8.5, color: str | None = None):
    ax.text(x, y, text, ha="left", va="center", fontsize=size,
            color=color or PALETTE["muted"])


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------


def finalize_figure(
    fig,
    out_stem: str | Path,
    *,
    formats: tuple[str, ...] = ("svg", "png", "pdf"),
    dpi: int = 300,
    pad: float = 0.02,
    close: bool = True,
) -> list[Path]:
    """Write one figure to every format, into the script's `figures/` folder.

    `out_stem` is a path without an extension. SVG is what the website loads,
    PNG is what READMEs embed, PDF is what goes into a paper.
    """
    stem = Path(out_stem)
    stem.parent.mkdir(parents=True, exist_ok=True)
    written = []
    for fmt in formats:
        path = stem.with_suffix(f".{fmt}")
        fig.savefig(path, format=fmt, dpi=dpi, bbox_inches="tight", pad_inches=pad)
        written.append(path)
    if close:
        plt.close(fig)
    for p in written:
        print(f"  wrote {p}")
    return written
